tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#cdd7ff",
        "on-primary-container": "#5c0008",
        "primary": "#ffb3ad",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#33343b",
        "on-secondary": "#002a78",
        "on-secondary-fixed-variant": "#003ea8",
        "primary-container": "#ff5451",
        "surface-container-low": "#191b22",
        "surface": "#111319",
        "on-tertiary-container": "#00311f",
        "inverse-on-surface": "#2e3037",
        "secondary-container": "#0053db",
        "primary-fixed-dim": "#ffb3ad",
        "error-container": "#93000a",
        "outline": "#ab8986",
        "tertiary-container": "#00a572",
        "on-surface-variant": "#e4beba",
        "background": "#111319",
        "on-background": "#e2e2ea",
        "surface-container-high": "#282a30",
        "tertiary-fixed-dim": "#4edea3",
        "surface-bright": "#373940",
        "on-surface": "#e2e2ea",
        "on-secondary-fixed": "#00174b",
        "inverse-surface": "#e2e2ea",
        "on-primary-fixed": "#410004",
        "inverse-primary": "#b91a24",
        "on-tertiary-fixed": "#002113",
        "on-tertiary": "#003824",
        "secondary-fixed-dim": "#b4c5ff",
        "surface-dim": "#111319",
        "on-tertiary-fixed-variant": "#005236",
        "surface-variant": "#33343b",
        "secondary": "#b4c5ff",
        "surface-container": "#1d1f26",
        "error": "#ffb4ab",
        "tertiary": "#4edea3",
        "on-primary": "#68000a",
        "surface-container-lowest": "#0c0e14",
        "surface-tint": "#ffb3ad",
        "primary-fixed": "#ffdad7",
        "secondary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#930013",
        "outline-variant": "#5b403e",
        "on-error": "#690005",
        "on-error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-compact": "0.5rem",
        "gutter": "1rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "margin-mobile": "0.75rem",
        "space-sm": "0.5rem",
        "margin": "1.5rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        "headline-sm": ["Barlow Condensed"],
        "headline-md": ["Barlow Condensed"],
        "label-tactical": ["Barlow Condensed"],
        "body-md": ["Inter"],
        "score-display-mobile": ["Barlow Condensed"],
        "control-action": ["Barlow Condensed"],
        "body-lg": ["Inter"],
        "score-display": ["Barlow Condensed"],
        "headline-lg": ["Barlow Condensed"],
        "timer-display": ["Barlow Condensed"],
        "headline-lg-mobile": ["Barlow Condensed"],
        "timer-display-mobile": ["Barlow Condensed"],
        "label-micro": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "0.03em", fontWeight: "700" }],
        "label-tactical": ["14px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "score-display-mobile": ["40px", { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "800" }],
        "control-action": ["22px", { lineHeight: "24px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "score-display": ["72px", { lineHeight: "72px", letterSpacing: "0.02em", fontWeight: "800" }],
        "headline-lg": ["36px", { lineHeight: "40px", letterSpacing: "0.02em", fontWeight: "700" }],
        "timer-display": ["96px", { lineHeight: "96px", letterSpacing: "0.04em", fontWeight: "800" }],
        "headline-lg-mobile": ["26px", { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "700" }],
        "timer-display-mobile": ["52px", { lineHeight: "52px", letterSpacing: "0.02em", fontWeight: "800" }],
        "label-micro": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }]
      }
    }
  }
}
